---
title: "git_01"
author: "Janette Quezada"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
I love the stillness of the wood:  
I love the music of the rill:  
I love to couch in pensive mood  
Upon some silent hill.  
Scarce heard, beneath yon arching trees,  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
From what old ballad, or from what rich frame  
Did you descend to glorify the earth?  
Was it from Chaucer’s singing book you came?  
Or did Watteau’s small brushes give you birth?  
Nothing so exquisite as that slight hand  
Could Raphael or Leonardo trace.  
Nor could the poets know in Fairyland  
The changing wonder of your lyric face.  
I would possess a host of lovely things,  
But I am poor and such joys may not be.  
So God who lifts the poor and humbles kings  
Sent loveliness itself to dwell with me.  

